services:
  debtmanagement.api:
    image: ${DOCKER_REGISTRY-}debtmanagementapi
    build:
      context: .
      dockerfile: DebtManagement.API/Dockerfile
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Desafio@1234
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Desafio@1234 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  sql_data:
